### ISSUE TITLE
How to clear the SelectedItem

### ISSUE THREAD

**Issue by rokorec31** [akgulebubekir/Maui.DataGrid#109]
**Describe the bug**
I have a use case where pressing a cell navigate to the detail page. However, the current situation is that when returning from the detail page to the list page, it is not possible to select the same cell again because the SelectedItem remains the same and does not trigger the OnSelectedItemChanged event.
When I set SelectedItem to null after navigated to the detail page, it causes a crash. Please give a help, thanks.

**To Reproduce**

View
```
<dg:DataGrid ItemsSource="{Binding Items}"
             SelectionEnabled="True"
             SelectedItem="{Binding SelectedItem}">
    <dg:DataGrid.Columns>
        <dg:DataGridColumn Title="Name" PropertyName="Name" />
    </dg:DataGrid.Columns>
</dg:DataGrid>
```

ViewModel
```
[ObservableProperty]
Item? selectedItem;

partial void OnSelectedItemChanged(Item? value)
{
    try {
        if (value is null)
            return;

        Shell.Current.GoToAsync(nameof(DetailPage));
    }
    finally {
        SelectedItem = null;
    }
}
```

**Screenshots**

StackTrace
```
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Maui.WeakEventManager.HandleEvent(Object sender, Object args, String eventName)
   at Maui.DataGrid.DataGrid.OnSelectionChanged(Object sender, SelectionChangedEventArgs e)
   at Microsoft.Maui.Controls.SelectableItemsView.SelectionPropertyChanged(SelectableItemsView selectableItemsView, SelectionChangedEventArgs args)
   at Microsoft.Maui.Controls.SelectableItemsView.SelectedItemPropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.SelectableItemsView.set_SelectedItem(Object value)
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewHandler`1.UpdateVirtualSingleSelection()
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewHandler`1.UpdateVirtualSelection()
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewHandler`1.PlatformSelectionChanged(Object sender, SelectionChangedEventArgs args)
   at WinRT._EventSource_global__Microsoft_UI_Xaml_Controls_SelectionChangedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, SelectionChangedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.SelectionChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Comment by symbiogenesis** [comment]
Looks like you are using CommunityToolkit.Mvvm

This is using a source generator to produce the public property from the backing field. You could try setting the backing field to be null instead of the public property.

Another possibility is that it has to do with the Shell navigation, and if you are really doing a master-detail approach then maybe what you need is something more like the Popup control from CommunityToolkit.Maui.

That control would be awaitable and return a value, if you like. That opens up a lot of options, and has a more predictable control flow.

Just some thoughts. If you can reproduce this problem with a minimal test case, and upload it as a new public repository on here, then I could try some more things.

**Comment by symbiogenesis** [comment]
Normal shell navigation isn't really supposed to involve executing more lines of code after the GoToAsync method. If you want to clear the selected item afterwards with normal shell navigation, the best place would be in the Appearing event of the page.
