### ISSUE TITLE
TargetInvocationException when switching underlying Item Source

### ISSUE THREAD

**Issue by tudoranghelina91** [akgulebubekir/Maui.DataGrid#81]
**Describe the bug**
TargetInvocationException gets thrown when having selection enabled for a single item and assigning the underlying ObservableCollection<T> to a new instance.

**To Reproduce**
1. Enable selection for the DataGrid control in the XAML file and assign an ItemsSource from a ViewModel
2. Select an item from the DataGrid making it the current selected item
3. Assign a new ObservableCollection<T> to the underlying ItemsSource

**Expected behavior**
The ObservableCollection<T> should be changed without throwing any error

**Screenshots**

![image](https://user-images.githubusercontent.com/16164903/222091135-8f118168-c0c2-4c9f-af05-f6cef440e03a.png)
![image](https://user-images.githubusercontent.com/16164903/222091254-6cd9cb70-b4f9-400b-9839-55d5f328e307.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**

**Additional context**

Exception Stack Trace:
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Maui.WeakEventManager.HandleEvent(Object sender, Object args, String eventName)
   at Microsoft.Maui.Controls.SelectableItemsView.SelectionPropertyChanged(SelectableItemsView selectableItemsView, SelectionChangedEventArgs args)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Maui.DataGrid.DataGrid.<>c.<.cctor>b__127_7(BindableObject b, Object o, Object n)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.SetProperty[T](T& field, T newValue, String propertyName)
   at WarehouseManagement.MAUI.ViewModels.InventoryItemsViewModel.set_InventoryItems(ObservableCollection`1 value) in C:\Users\tanghelina\source\repos\Github\WarehouseManagement\src\WarehouseManagement.MAUI\ViewModels\InventoryItemsViewModel.cs:line 26

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```

**Comment by symbiogenesis** [comment]
What version are you running? Can you reproduce this if you pull this codebase into your repo, rather than using the nuget?
